### ISSUE TITLE
Java exception thrown inFiji on first use

### ISSUE THREAD

**Issue by jblugagne** [fjug/MoMA#41]
Hi!

I have been trying to install and use MoMA on Fiji (fresh install, up-to-date). After installation via ImageJ's updater as described in the installation guide, when I want to run MoMA for the first time (Plugins > MoMA > MoMA application processing a folder/image/current), instead of the pop-up window asking for a Gurobi license I get the following exception:

```
(Fiji Is Just) ImageJ 2.0.0-rc-69/1.52i; Java 1.8.0_66 [64-bit]; Linux 4.17.19-100.fc27.x86_64; 150MB of 20667MB (<1%)
 
java.lang.NoClassDefFoundError: gurobi/GRBException
    at com.jug.fijiplugins.MotherMachineDefaultPipelinePlugin.run(MotherMachineDefaultPipelinePlugin.java:40)
    at ij.IJ.runUserPlugIn(IJ.java:228)
    at ij.IJ.runPlugIn(IJ.java:192)
    at ij.Executer.runCommand(Executer.java:137)
    at ij.Executer.run(Executer.java:66)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: gurobi.GRBException
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 6 more


```

I have tried this both on Linux (Fedora 27) and MacOSX and I get the same exception. I have tried installing Gurobi separately and then launching MoMA but to no avail. There are a couple (minor) things that could be updated also in the install guide on the wiki.

Thanks!

**Comment by julou** [comment]
Hi,

I'm unfortunately not the one who can fix the bug.
What I can report is that the version we use for "production" is the one-before-last (MotherMachine_-0.10.9.jar) which you can download and manually copy to your plugins directory from https://sites.imagej.net/MoMA/plugins/

As far as I understand, the last version was an attempt to refactor it without including dependencies, but I'm not sure whether it has ever been used apart from by the dev…

To give it a brighter outlook, a new dev will join us very soon, full time on this project!

**Comment by julou** [comment]
Again I can only comment on how we use it for our analysis...

Since you've installed Gurobi independently, you should be able to run MoMa from the command line: to give it a try you can manually crop and save a stack of a single growth channel in IJ, then follow https://github.com/fjug/MoMA/wiki/Running-MoMA-from-the-command-line

You can of course also run the preprocessing from the command line as well:
https://github.com/fjug/MoMA/wiki/Preprocessing-From-The-Command-Line

**Comment by danychauvin** [comment]
I installed successfully MoMA today using @julou solution:
- using MoMA 0.10.9.jar.
- I could not make it work with the oldest Gurobi version available on gurobi's website. I had to install gurobi 6.5.2 instead, that I had archived previously (a Gurobi technical assistant refused to send me a download link unfortunately).

@jblugagne from the "could not initialize gurobi" message you got, it seems that you did not set path for your gurobi setup. Did you add setup your gurobi license and the following comands to your Fedora equivalent of .bashrc?

export GUROBI_HOME="/opt/gurobi652/linux64"
export PATH="${PATH}:${GUROBI_HOME}/bin"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${GUROBI_HOME}/lib"
export GRB_LICENSE_FILE=/your/path/to/your/gurobi/license/gurobi.lic

**Comment by jblugagne** [comment]
Hi, I've tried a few more things in the past few days but I think Gurobi versions >=7 just aren't compatible with MoMa, and I couldn't get my hands on version 6.5.2

Are there plans to update MoMa to work with more recent versions of gurobi?

**Comment by jblugagne** [comment]
Sorry, I hadn't understood what @julou was suggesting, I am now able to run MoMa with the command line version.

Thank you for the suggestion and help! I am going to close this issue
